build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: ChatGPT Terminal"
  org.opencontainers.image.description: "Terminal interface for OpenAI's Codex CLI"
  org.opencontainers.image.source: "https://github.com/openai/openai-codex"
  org.opencontainers.image.licenses: "MIT"